export const menuItems = [
  {
    key: "home",
    title: "홈",
    url: "/home",
    fncClick: Function,
  },
  {
    key: "project",
    title: "시공사례",
    url: "/project",
    fncClick: Function,
    sub: [
      {
        key: "residence",
        title: "주거공간",
        url: "/project?category=residence",
        fncClick: Function,
      },
      {
        key: "mercantile",
        title: "상업공간",
        url: "/project?category=mercantile",
        fncClick: Function,
      },
      {
        key: "architecture",
        title: "친환경 건축",
        url: "/project?category=architecture",
        fncClick: Function,
      },
    ],
  },
  {
    key: "showroom",
    title: "직영쇼룸",
    url: "/showroom",
    fncClick: Function,
  },
  {
    key: "furniture",
    title: "직영가구",
    url: "/furniture",
    fncClick: Function,
  },
  {
    key: "notice",
    title: "공지사항",
    url: "/notice",
    fncClick: Function,
  },
];

export const projectsItems = [
  {
    id: 1,
    title: "모던 아파트 거실 인테리어",
    year: 2021,
    price: 52000000,
    img: "/image/mock/거실.png",
    desc: "평당 162만원",
    py: 32,
    label: "주거공간",
  },
  {
    id: 2,
    title: "럭셔리 건물 리모델링",
    year: 2022,
    price: null,
    img: "/image/mock/건물3.png",
    desc: "고객 요청으로 비공개",
    py: 34,
    label: "주거공간",
  },
  {
    id: 3,
    title: "심플 주방 인테리어",
    year: 2020,
    price: 48000000,
    img: "/image/mock/주방.png",
    desc: "평당 145만원",
    py: 33,
    label: "주거공간",
  },
  {
    id: 4,
    title: "카페 스타일 사무실",
    year: 2023,
    price: 61000000,
    img: "/image/mock/사무실.png",
    desc: "평당 174만원",
    py: 35,
    label: "상업공간",
  },
  {
    id: 5,
    title: "모던 카페 인테리어",
    year: 2022,
    price: 57000000,
    img: "/image/mock/카페.png",
    desc: "평당 158만원",
    py: 36,
    label: "상업공간",
  },
  {
    id: 6,
    title: "프리미엄 학원 리모델링",
    year: 2021,
    price: 53000000,
    img: "/image/mock/학원.png",
    desc: "평당 166만원",
    py: 32,
    label: "상업공간",
  },
  {
    id: 7,
    title: "내추럴 스타일 욕실",
    year: 2020,
    price: null,
    img: "/image/mock/욕실.png",
    desc: "고객 요청으로 비공개",
    py: 34,
    label: "주거공간",
  },
  {
    id: 8,
    title: "모던 독서실 인테리어",
    year: 2023,
    price: 56000000,
    img: "/image/mock/독서실.png",
    desc: "평당 170만원",
    py: 33,
    label: "상업공간",
  },
  {
    id: 9,
    title: "심플 자녀방 인테리어",
    year: 2021,
    price: 50000000,
    img: "/image/mock/자녀방.png",
    desc: "평당 152만원",
    py: 35,
    label: "주거공간",
  },
  {
    id: 10,
    title: "트렌디 오피스 인테리어",
    year: 2022,
    price: 62000000,
    img: "/image/mock/사무실.png",
    desc: "평당 172만원",
    py: 36,
    label: "상업공간",
  },
  {
    id: 11,
    title: "아늑한 식당 인테리어",
    year: 2023,
    price: 59000000,
    img: "/image/mock/식당.png",
    desc: "평당 164만원",
    py: 32,
    label: "상업공간",
  },
  {
    id: 12,
    title: "모던 주택 인테리어",
    year: 2021,
    price: null,
    img: "/image/mock/주택3.png",
    desc: "고객 요청으로 비공개",
    py: 34,
    label: "상업공간",
  },
  {
    id: 13,
    title: "럭셔리 건물 리모델링",
    year: 2022,
    price: 55000000,
    img: "/image/mock/건물1.png",
    desc: "평당 168만원",
    py: 33,
    label: "상업공간",
  },
  {
    id: 14,
    title: "내추럴 건물 인테리어",
    year: 2020,
    price: 51000000,
    img: "/image/mock/건물2.png",
    desc: "평당 154만원",
    py: 35,
    label: "상업공간",
  },
  {
    id: 15,
    title: "프리미엄 주택 리모델링",
    year: 2023,
    price: 63000000,
    img: "/image/mock/주택1.png",
    desc: "평당 175만원",
    py: 36,
    label: "주거공간",
  },
];

export const pyFilter: { key: string; label: string }[] = [
  { key: "py20", label: "20평형" },
  { key: "py30", label: "30평형" },
  { key: "py40", label: "40평형" },
  { key: "py50", label: "50평형" },
  { key: "py60", label: "60평형" },
  { key: "pyOthers", label: "그 외 평형" },
];
export const typeFilter: { key: string; label: string }[] = [
  { key: "apt", label: "아파트" },
  { key: "house", label: "주택" },
];


export const notices = [
  {
    id: 1,
    title: "새로운 기능 업데이트 안내",
    date: "2025-08-25",
    summary: "이번 업데이트에서는 새로운 기능과 버그 수정이 포함되었습니다...",
  },
  {
    id: 2,
    title: "버그 수정 안내",
    date: "2025-08-26",
    summary: "이번 업데이트에서는 여러 가지 버그가 수정되었습니다...",
  },
  {
    id: 3,
    title: "시스템 점검 안내",
    date: "2025-08-24",
    summary:
      "정기 시스템 점검이 예정되어 있습니다. 이용에 참고 부탁드립니다...",
  },
  {
    id: 4,
    title: "서비스 이용약관 변경 안내",
    date: "2025-08-23",
    summary:
      "서비스 이용약관이 일부 변경되었습니다. 자세한 내용을 확인해주세요...",
  },
  {
    id: 5,
    title: "신규 서비스 출시 안내",
    date: "2025-08-22",
    summary:
      "새로운 서비스가 출시되었습니다. 많은 이용 부탁드립니다...새로운 서비스가 출시되었습니다. 많은 이용 부탁드립니다...새로운 서비스가 출시되었습니다. 많은 이용 부탁드립니다...새로운 서비스가 출시되었습니다. 많은 이용 부탁드립니다...새로운 서비스가 출시되었습니다. 많은 이용 부탁드립니다...",
  },
];

export const furnitures = [
  {
    id: 1,
    name: "JJ Mobilia",
    location: "대구광역시 수성구 달구벌대로 2478 1층 2~3F",
    hours: "평일 09:00~18:00 / 토 10:00~17:00 / 일 10:00~16:00",
    info: "방문 전 상담예약을 하셔야 매니저와의 인테리어 상담이 가능합니다.",
    image: "/image/mock/가구점 이미지.png",
  },
  {
    id: 2,
    name: "불성점",
    location: "대구광역시 북구 칠곡군 609 2~3F",
    hours: "평일 09:00~18:00 / 토 10:00~17:00 / 일 10:00~16:00",
    info: "방문 전 상담예약을 하셔야 견적상담이 가능하며, 예약없이 방문하시면 견적 상담없이 매장 내 자재 무드보드 및 키오스크 등의 체험은 가능합니다.",
    image: "/image/mock/회사 내부 이미지.png",
  },
];
