export const menuItems = [
  {
    key: "home",
    title: "홈",
    url: "/home",
    fncClick: Function,
  },
  {
    key: "project",
    title: "시공사례",
    url: "/project",
    fncClick: Function,
    sub: [
      {
        key: "resident",
        title: "주거공간",
        url: "/project?category=resident",
        fncClick: Function,
      },
      {
        key: "commercial",
        title: "상업공간",
        url: "/project?category=commercial",
        fncClick: Function,
      },
      {
        key: "echo",
        title: "친환경 건축",
        url: "/project?category=echo",
        fncClick: Function,
      },
    ],
  },
  {
    key: "showroom",
    title: "직영쇼룸",
    url: "/showroom",
    fncClick: Function,
  },
  {
    key: "furniture",
    title: "직영가구",
    url: "/furniture",
    fncClick: Function,
  },
  {
    key: "notice",
    title: "공지사항",
    url: "/notice",
    fncClick: Function,
  },
];

export const projectsItems = [
  {
    id: 1,
    title: "모던 아파트 거실 인테리어",
    year: 2021,
    price: 52000000,
    img: "/image/mock/거실.png",
    desc: "평당 162만원",
    py: 32,
    label: "주거공간",
  },
  {
    id: 2,
    title: "럭셔리 건물 리모델링",
    year: 2022,
    price: null,
    img: "/image/mock/건물3.png",
    desc: "고객 요청으로 비공개",
    py: 34,
    label: "주거공간",
  },
  {
    id: 3,
    title: "심플 주방 인테리어",
    year: 2020,
    price: 48000000,
    img: "/image/mock/주방.png",
    desc: "평당 145만원",
    py: 33,
    label: "주거공간",
  },
  {
    id: 4,
    title: "카페 스타일 사무실",
    year: 2023,
    price: 61000000,
    img: "/image/mock/사무실.png",
    desc: "평당 174만원",
    py: 35,
    label: "상업공간",
  },
  {
    id: 5,
    title: "모던 카페 인테리어",
    year: 2022,
    price: 57000000,
    img: "/image/mock/카페.png",
    desc: "평당 158만원",
    py: 36,
    label: "상업공간",
  },
  {
    id: 6,
    title: "프리미엄 학원 리모델링",
    year: 2021,
    price: 53000000,
    img: "/image/mock/학원.png",
    desc: "평당 166만원",
    py: 32,
    label: "상업공간",
  },
  {
    id: 7,
    title: "내추럴 스타일 욕실",
    year: 2020,
    price: null,
    img: "/image/mock/욕실.png",
    desc: "고객 요청으로 비공개",
    py: 34,
    label: "주거공간",
  },
  {
    id: 8,
    title: "모던 독서실 인테리어",
    year: 2023,
    price: 56000000,
    img: "/image/mock/독서실.png",
    desc: "평당 170만원",
    py: 33,
    label: "상업공간",
  },
  {
    id: 9,
    title: "심플 자녀방 인테리어",
    year: 2021,
    price: 50000000,
    img: "/image/mock/자녀방.png",
    desc: "평당 152만원",
    py: 35,
    label: "주거공간",
  },
  {
    id: 10,
    title: "트렌디 오피스 인테리어",
    year: 2022,
    price: 62000000,
    img: "/image/mock/사무실.png",
    desc: "평당 172만원",
    py: 36,
    label: "상업공간",
  },
  {
    id: 11,
    title: "아늑한 식당 인테리어",
    year: 2023,
    price: 59000000,
    img: "/image/mock/식당.png",
    desc: "평당 164만원",
    py: 32,
    label: "상업공간",
  },
  {
    id: 12,
    title: "모던 주택 인테리어",
    year: 2021,
    price: null,
    img: "/image/mock/주택3.png",
    desc: "고객 요청으로 비공개",
    py: 34,
    label: "상업공간",
  },
  {
    id: 13,
    title: "럭셔리 건물 리모델링",
    year: 2022,
    price: 55000000,
    img: "/image/mock/건물1.png",
    desc: "평당 168만원",
    py: 33,
    label: "상업공간",
  },
  {
    id: 14,
    title: "내추럴 건물 인테리어",
    year: 2020,
    price: 51000000,
    img: "/image/mock/건물2.png",
    desc: "평당 154만원",
    py: 35,
    label: "상업공간",
  },
  {
    id: 15,
    title: "프리미엄 주택 리모델링",
    year: 2023,
    price: 63000000,
    img: "/image/mock/주택1.png",
    desc: "평당 175만원",
    py: 36,
    label: "주거공간",
  },
];
