export const menuItems = [
  {
    key: "home",
    title: "홈",
    url: "/",
    fncClick: Function,
  },
  {
    key: "project",
    title: "시공사례",
    url: "/project",
    fncClick: Function,
    sub: [
      {
        key: "echo",
        title: "친환경 건축",
        url: "/project?category=echo",
        fncClick: Function,
      },
      {
        key: "resident",
        title: "주거공간",
        url: "/project?category=resident",
        fncClick: Function,
      },
      {
        key: "commercial",
        title: "상업공간",
        url: "/project?category=commercial",
        fncClick: Function,
      },
    ],
  },
  {
    key: "showroom",
    title: "직영쇼룸",
    url: "/showroom",
    fncClick: Function,
  },
  {
    key: "furniture",
    title: "직영가구",
    url: "/furniture",
    fncClick: Function,
  },
  {
    key: "notice",
    title: "공지사항",
    url: "/notice",
    fncClick: Function,
  },
];

export const projectsItems = [
  {
    title: "범어청구하이츠 32PY",
    year: 2000,
    price: "49,000,000",
    img: "/image/mock/건축.png",
    desc: "평당 153만원",
  },
  {
    title: "범어숲 화성파크드림S 34PY",
    year: 2013,
    price: "비공개",
    img: "/image/mock/상업.png",
    desc: "고객 요청으로 비공개",
  },
  {
    title: "세천한라비발디 33PY",
    year: 2016,
    price: "54,328,000",
    img: "/image/mock/주방.png",
    desc: "평당 164만원",
  },
  {
    title: "범어청구하이츠 35PY",
    year: 2002,
    price: "52,000,000",
    img: "/image/mock/화장실.png",
    desc: "평당 150만원",
  },
  {
    title: "범어숲 화성파크드림S 36PY",
    year: 2015,
    price: "60,000,000",
    img: "/image/mock/건축.png",
    desc: "평당 166만원",
  },
  {
    title: "범어청구하이츠 32PY",
    year: 2000,
    price: "49,000,000",
    img: "/image/mock/건축.png",
    desc: "평당 153만원",
  },
  {
    title: "범어숲 화성파크드림S 34PY",
    year: 2013,
    price: "비공개",
    img: "/image/mock/상업.png",
    desc: "고객 요청으로 비공개",
  },
  {
    title: "세천한라비발디 33PY",
    year: 2016,
    price: "54,328,000",
    img: "/image/mock/주방.png",
    desc: "평당 164만원",
  },
  {
    title: "범어청구하이츠 35PY",
    year: 2002,
    price: "52,000,000",
    img: "/image/mock/화장실.png",
    desc: "평당 150만원",
  },
  {
    title: "범어숲 화성파크드림S 36PY",
    year: 2015,
    price: "60,000,000",
    img: "/image/mock/건축.png",
    desc: "평당 166만원",
  },
  {
    title: "범어청구하이츠 32PY",
    year: 2000,
    price: "49,000,000",
    img: "/image/mock/건축.png",
    desc: "평당 153만원",
  },
  {
    title: "범어숲 화성파크드림S 34PY",
    year: 2013,
    price: "비공개",
    img: "/image/mock/상업.png",
    desc: "고객 요청으로 비공개",
  },
  {
    title: "세천한라비발디 33PY",
    year: 2016,
    price: "54,328,000",
    img: "/image/mock/주방.png",
    desc: "평당 164만원",
  },
  {
    title: "범어청구하이츠 35PY",
    year: 2002,
    price: "52,000,000",
    img: "/image/mock/화장실.png",
    desc: "평당 150만원",
  },
  {
    title: "범어숲 화성파크드림S 36PY",
    year: 2015,
    price: "60,000,000",
    img: "/image/mock/건축.png",
    desc: "평당 166만원",
  },
];

export const imageItems = [
  { title: "건축", description: "건축 이미지", src: "/image/mock/건축.png" },
  { title: "상업", description: "상업 이미지", src: "/image/mock/상업.png" },
  { title: "주방", description: "주방 이미지", src: "/image/mock/주방.png" },
  {
    title: "화장실",
    description: "화장실 이미지",
    src: "/image/mock/화장실.png",
  },
];
